name: Deploy to Cloud Function

on:
  push:
    branches: [main]

jobs:
  deploy-cf:
    name: Deploy to Cloud Function
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Configure Workload Identity Federation via a credentials file.
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@main
        with:
          create_credentials_file: true
          activate_credentials_file: false
          workload_identity_provider: projects/1072832062356/locations/global/workloadIdentityPools/github-actions-pool/provider/token-provider
          service_account: github-actions@sandbox-toga4-211010cf.iam.gserviceaccount.com

      - id: cred
        name: Read credentials
        run: |
          echo "::set-output name=credentials::$(cat ${{steps.auth.outputs.credentials_file_path}})"

      - id: Deploy
        uses: toga4/deploy-cloud-functions@main
        with:
          project_id: sandbox-toga4-211010cf
          name: SandboxCFDeploy
          runtime: go116
          credentials: ${{ steps.cred.outputs.credentials }}
