name: Deploy to Cloud Function

on:
  push:
    branches: [main]

jobs:
  deploy-cf:
    name: Deploy to Cloud Function
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Configure Workload Identity Federation via a credentials file.
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@main
        with:
          create_credentials_file: true
          activate_credentials_file: false
          workload_identity_provider: projects/1072832062356/locations/global/workloadIdentityPools/github-actions-pool/providers/token-provider
          service_account: github-actions@sandbox-toga4-211010cf.iam.gserviceaccount.com

      - id: cred
        name: Read credentials
        run: |
          echo "::set-output name=credentials::$(cat ${{steps.auth.outputs.credentials_file_path}})"

      - id: Deploy
        uses: toga4/deploy-cloud-functions@feature/secrets-test
        with:
          project_id: sandbox-toga4-211010cf
          name: SandboxCFDeploy
          runtime: go116
          credentials: ${{ steps.cred.outputs.credentials }}
          secrets: |
            ENV_VAR1=FOO_SECRET:1
            ENV_VAR2=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET:1
            ENV_VAR3=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET/versions/1
            ENV_VAR4=FOO_SECRET:latest
            ENV_VAR5=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET:latest
            ENV_VAR6=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET/versions/latest
            /etc/secrets:/SECRET1=FOO_SECRET:1
            /secrets:/SECRET2=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET:1
            /etc/secrets:/SECRET3=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET/versions/1
            /secrets/SECRET4=FOO_SECRET:latest
            /etc/secrets/SECRET5=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET:latest
            /secrets/SECRET6=projects/sandbox-toga4-211010cf/secrets/FOO_SECRET/versions/latest
